### ISSUE TITLE
Declaracion de la situacion del problema

### ISSUE THREAD

**Issue by HaroldAcevedo** [HaroldAcevedo/equipo-9_VT_PPI2020#4]

**Comment by Esteb4nJG** [comment]
DECLARACIÓN DE LA SITUACIÓN:

En el colegio vida para todos hay una necesidad la cual es: como poderse transportar para ir a el colegio no solo a pie. por que a algunos estudiantes les coge la tarde. Estos son causados ya que varios estudiantes de la instrucción vida para todos de grados superiores a 8 tienen la necesidad de transportarse para no llegar tarde a el colegio y esto da para obtener un resultado positivo en algunos estudiantes que llegan tarde ya que pueden utilizar el medio de transporte y esto nos ayuda a nosotros como a ellos.

**Comment by Esteb4nJG** [comment]
DECLARACIÓN DE LA SITUACIÓN DEL PROBLEMA:
Los habitantes DEL BARRIO CAICEDO no saben cómo tener una alimentación balanceada y se ha elevado el numero de personas que no le prestan atención a su salud y comen más o menos de la cantidad de alimento necesario para su correcto funcionamiento gracias a la llegada de la cuarentena IMPUESTA POR EL GOBIERNO por culpa del CO-VID 19,  por esto buscamos una forma de ayudar a las personas a tener una alimentación correcta y no tengan problemas en algún momento de sus vidas gracias a sus malos hábitos.
