### ISSUE TITLE
Identificacion de los interesados

### ISSUE THREAD

**Issue by HaroldAcevedo** [HaroldAcevedo/equipo-9_VT_PPI2020#5]

**Comment by Esteb4nJG** [comment]
![image](https://user-images.githubusercontent.com/67934412/90997913-70dbfe00-e588-11ea-97f5-173d759da289.png)

**Comment by HaroldAcevedo** [comment]
![Descripcion de un interesado](https://user-images.githubusercontent.com/66481437/91589640-b2213480-e91f-11ea-9e2d-d3aa3b245f3b.PNG)

**Comment by HaroldAcevedo** [comment]
![TB](https://user-images.githubusercontent.com/66481437/91619631-393bd000-e953-11ea-8ada-7050ecf10184.PNG)

**Comment by HaroldAcevedo** [comment]
![23456](https://user-images.githubusercontent.com/66481437/91622361-722c7280-e95c-11ea-8994-2cd0e484f5c3.PNG)
