### ISSUE TITLE
Vision del producto

### ISSUE THREAD

**Issue by HaroldAcevedo** [HaroldAcevedo/equipo-9_VT_PPI2020#6]

**Comment by Esteb4nJG** [comment]
Visión:
Los habitantes del barrio" CAICEDO" no saben cómo tener una alimentación balanceada y se ha elevado el numero de personas que no le prestan atención a su salud y comen más o menos de la cantidad de alimento necesario para su correcto funcionamiento gracias a la llegada de la cuarentena IMPUESTA POR EL GOBIERNO por culpa del COVID-19,  por esto de ayudar a las personas a tener una alimentación correcta y no tengan problemas en algún momento de sus vidas gracias a sus malos hábitos.

**Comment by Esteb4nJG** [comment]
VISIÓN:
Nutrición Life es una plataforma dirigida a las personas residentes en Medellín que desean obtener una buena alimentación ya sea porque sufren de alguna enfermedad relacionada con trastornos alimenticios o comienzan a preocuparse por que alimentos está ingiriendo cada día, a diferencia de otras plataformas que informan sobre como tener una buena alimentación nuestro proyecto realizara un seguimiento día a día de tu alimentación y mostrara por medio  de una gráfica el avance que has tenido durante el transcurso de el tiempo que llevas en la plataforma, por eso te pedimos nos apoyes. Somos Nutrición Life.

**Comment by HaroldAcevedo** [comment]
![Vision del producto](https://user-images.githubusercontent.com/66481437/91588398-b5b3bc00-e91d-11ea-8cdf-784adf9f348e.PNG)

**Comment by HaroldAcevedo** [comment]
![Captura](https://user-images.githubusercontent.com/66481437/91593563-062f1780-e926-11ea-9bcf-9819a8c2ff69.PNG)

**Comment by HaroldAcevedo** [comment]
![VP](https://user-images.githubusercontent.com/66481437/91599981-ccadda80-e92c-11ea-817d-f7b6430f2fd4.PNG)

**Comment by HaroldAcevedo** [comment]
![PRO](https://user-images.githubusercontent.com/66481437/91615227-b7df4000-e948-11ea-92de-151e15b921b4.PNG)

**Comment by HaroldAcevedo** [comment]
![pro2](https://user-images.githubusercontent.com/66481437/91615425-27552f80-e949-11ea-8ab6-4b5510b8f102.PNG)

**Comment by HaroldAcevedo** [comment]
![293](https://user-images.githubusercontent.com/66481437/91615819-0b9e5900-e94a-11ea-9485-87d2b404610b.PNG)

**Comment by HaroldAcevedo** [comment]
![234](https://user-images.githubusercontent.com/66481437/91619527-eb26cc80-e952-11ea-851a-f27ef7623261.PNG)

**Comment by HaroldAcevedo** [comment]
![2934](https://user-images.githubusercontent.com/66481437/91620701-52924b80-e956-11ea-8fdd-2f1e144860ab.PNG)
